{% set version = "1.3.26" %}

package:
  name: openvisus
  version: {{ version }}
  
source:
  git_rev: 1.3.12
  url: https://github.com/sci-visus/OpenVisus/archive/{{ version }}.tar.gz
  sha256: 538bda083476c2d3bc6705a1d58f161764a61b2579fbe5af2ee3fd67cd53961d

build:
  number: 0
  skip: True  # [win]
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - swig
    - cmake
  host:
    - python  
    - pip
    - numpy
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - OpenVisus

about:
  home: http://github.com/sci-visus/OpenVisus
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Open Source Implementation of VISUS'
  description: The mission of ViSUS.org is to provide support for the scientific community with Big Data, management, analysis and visualization tools

extra:
  recipe-maintainers:
    - doutriaux1
    - spetruzza
    - scrgiorgio
