travis:
  secure:
    BINSTAR_TOKEN: dYOGNpHp/ikZA+hZigewwuAIIqLnddFaq20Bwl7yqI0sObJ+pDPVDnsm/nybsxWCgWk5gMc9ZssIOt2Yd5pIrjZdJ6jZYQuJf4DOnRoM2AgWLHlAZK4tnTthaXGq8rpGf8njXVLlkwAfM//PSMGL5+N+p+pbNc6wThXLoLN0i+ycRPtuapwdsUO/OO2Wzs032+NEfxC7qUsBffEs/xt737ZtzJSJRDgtIllRGvx+JAVrwu76E+RrBcYdkzETn/cEV/IO4xTNoXBn6EvEjcZPB9Bx+NXZ4H1y4IwFRhkxhtXzZ2UVicXeq7l4pLL1yjdV8uxHn6RA2xQdE7EAnhrOST8n0gP7Nn/JvLVdWEczOEWrf1JdhYSOkwrb49HXNOO5I8Z74WFjMH+fZMdB6Hw1VoxjW2U71A0T+0d/rowKW6154AKFyNayXIMzVm1zUrvwheWaGcAozQXw3NRzrj/wrLW+zK+4reebJMzBdTnK6I4ZQ51aqqv0VsvZOSzqkIWGHLtsoe50cQRtFkauNvChAceKqmm6F2mOY7beFqZnvwl5kJXoKzj581LbC4ac5Wy0CsPHAtrrrLMFBYMsjzB8bkhxKCoQY05OWPksepCq+nfPgtO+EMSmttzCcMeBLrvjg/LpbxwjLS4P9UvIa65AIKgyovcDdttZM6U2EZKCaY0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
