travis:
  secure:
    BINSTAR_TOKEN: XsWMfTbgyF2ykbOgNeYIjCcAVhSlM/V8ESqUYnfwv3/MO/zNjd1XR5DrYRByswfCDS4k0XBjqU4tLYnfGNO0mCmMMtoGwIG0+0/vMZ3FGu27Stq7WophRPQ7EfPHSb7AxlwyV1++SCTZZyFDvhpyh/O7IZ5C3Y44LXecspqaKarI1Ed0VzA83sw4T9mDHaqjNEBDtsZirjtXG0Cyiy0/wlfiDHFMDjzzglQe5l32B/vI7jrCDgvMr4y9blZ9rAcG5y0axO1mf9lbEc1QsDCCPJisaxv4eEI9rWd7s9OGoF/Q+8HohH9s+Xavax4e9s4B6Z7QpAhPfq2Z4I/MeThdSDQfGDfLFl1dLj9EyI+sTEntW/BZ+eXYIAL4n0PhV4K+ZjHEflTzDrsvNQSi1/PPB2EzI89mRC4WI/JRpmD19vyrw+2UYkwyooxmN+NGXGeZRBPdtoLuIbUguaN8Ud32lsh9FpEMHUBokWTDFS2S1L65owbhKfTn/XQLiZq70Xv8g+G08h8W7z0YN3ixnj7rO68neUExmHYmP+dawQKRRSxcnH4qzM/nN23WyT2PA6j3PcYOIh1LVRdIMJ7gTMKfhH6h/7tNrJd0fPXXzTQkHDAnYN3jd/z3rzKAF2GW9zpaggOINyOgJSuLEtpCSjtR5Aqtgs7+8v7NClqa+eSFSxM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
